@startuml
left to right direction
actor "Mahasiswa" as m
actor "Administrator" as a

rectangle "Ganesha Event System" {
  usecase "Register" as UC1
  usecase "Login" as UC2
  usecase "Melihat Daftar Event" as UC3
  usecase "Melihat Detail Event" as UC4
  usecase "Mendaftar Event" as UC5
  usecase "Upload Bukti Pembayaran" as UC6
  usecase "Download Sertifikat" as UC7
  
  usecase "Kelola Data Event" as UC8
  usecase "Verifikasi Pendaftaran" as UC9
  usecase "Absensi Peserta" as UC10

  UC4 <.. UC5 : <<extend>>
  UC5 <.. UC6 : <<extend>>
}

m --> UC1
m --> UC2
m --> UC3
m --> UC4
m --> UC7

a --> UC2
a --> UC8
a --> UC9
a --> UC10
@enduml
